server:
  port: 80

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.185.22:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service-router
          uri: lb://admin-serivce   #转发的服务名称，lb为负载均衡
          predicates:               # 断言
            - Path=/admin/**
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      datasource:
        ds1.nacos:
          serverAddr: 120.26.185.22:8848
          namespace: b0c3478f-55da-4203-ba59-3c075f1d3a0b
          dataId: gw-flow
          ruleType: gw-flow
        ds2.nacos:
          serverAddr: 120.26.185.22:8848
          namespace: b0c3478f-55da-4203-ba59-3c075f1d3a0b
          dataId: api-group
          ruleType: gw-api-group